---
apiVersion: bacman.io/baclet/v1alpha1
kind: BacletConfig

spec:
  jobs:
    - name: test-backup
      schedule: '*/5 * * * *'  # every 5 minutes
      archiveJob:
        src: /tmp/backup
        dest: /tmp/backup.tgz
        compression: xz
