---
apiVersion: bacman.io/baclet/v1alpha1
kind: BacletConfig

spec:
  destinations:
    - name: local-dir
      localPathDestination:
        path: /tmp/backups

    # - name: config-bucket
    #   s3Destination:
    #     bucket: hbjy-home-backup
    #     prefix: config/

  jobs:
    - name: xdg-config-home
      schedule: '* * * * * *'  # every 5 minutes
      destination: local-dir
      archiveJob:
        src: /home/hayden/.config
