---
on:
  push:
    branches:
      - '**'
    paths:
      - 'baclet/**'
      - '.github/workflows/baclet-build.yaml'
  pull_request:
    paths:
      - 'baclet/**'
      - '.github/workflows/baclet-build.yaml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy,rustfmt
          override: true

      - uses: Swatinem/rust-cache@v1

      - run: cargo build --release --verbose
        working-directory: ./baclet

      - uses: actions/upload-artifact@v3
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          name: baclet-linux-amd64
          path: baclet/target/release/baclet

      - uses: actions/upload-artifact@v3
        if: ${{ matrix.os == 'macos-latest' }}
        with:
          name: baclet-darwin-amd64
          path: baclet/target/release/baclet

      - uses: actions/upload-artifact@v3
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          name: baclet-windows-amd64
          path: baclet/target/release/baclet.exe
