---
on:
  push:
    branches:
      - '**'
    paths:
      - 'baclet/**'
      - '.github/workflows/baclet-clippy.yaml'
  pull_request:
    paths:
      - 'baclet/**'
      - '.github/workflows/baclet-clippy.yaml'

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Clippy
        working-directory: ./baclet
        run: cargo clippy --all-targets --all-features
