---
on:
  push:
    branches:
      - '**'
    paths:
      - 'baclet/**'
      - '.github/workflows/baclet-build.yaml'
  pull_request:
    paths:
      - 'baclet/**'
      - '.github/workflows/baclet-build.yaml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Build
        working-directory: ./baclet
        run: cargo build --release --verbose

      - uses: actions/upload-artifact@v3
        with:
          name: baclet-${{ matrix.os }}
          path: baclet/target/release/baclet
