---
on:
  push:
    branches:
      - '**'
    paths:
      - 'baclet/**'
  pull_request:
    paths:
      - 'baclet/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cd baclet && cargo build --release
      - uses: actions/upload-artifact@v3
        with:
          name: baclet-${{ matrix.os }}
          path: baclet/target/release/baclet
